apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "${PRODUCTION}"

labels:
- includeSelectors: true
  pairs:
    app: cloud
    env: prod

resources:
- infra/
- storage/
- mariadb/
- secrets/
- configmap/
- ../../base
- ingress/
